### ISSUE TITLE
Contact Section

### ISSUE THREAD

**Issue by MikeGShelby** [MikeGShelby/portfolio-react#2]
**Should include the following fields in a form:**
- Name
- Email address
- Message

**Validation**

- Moving cursor out of one of the form fields without entering text will display a notification that the field is required
- Entering invalid email address will display notification that invalid email has been entered

**Comment by Godwindaniel10** [comment]
Hi, I'm Godwin, will be glad to work on the contact section 😏
@MikeGShelby  should I dive in?

**Comment by MikeGShelby** [comment]
> Hi, I'm Godwin, will be glad to work on the contact section 😏
> @MikeGShelby should I dive in?

Hi Godwin. 
Thank you for the response, but this is just a project that I'm working on for a web development course. :) 
May I ask how you came across this repository? Is it being shared somewhere on GitHub?

**Comment by Godwindaniel10** [comment]
oops ok, just saw it while going through ( good first issue label ). 


happy coding

**Comment by Darsh2987** [comment]
Hi, I was looking at the issues on this repo which I found by searching "Github Issues" and was quite excited to contribute to,  however from reading the comments, you say that this is a project that your working on and implying that these issues aren't actually issues for people to contribute to?!

Perhaps you should close or delete them all, and not to be rude but I think that you shouldn't of put those tasks as issues in the first place... they aren't really issues instead they are features/parts of the site that you are working on.

**Comment by Godwindaniel10** [comment]
I was looking forward to say that as well, just have to comply. 

you're right @Darsh2987

**Comment by MikeGShelby** [comment]
> Hi, I was looking at the issues on this repo which I found by searching "Github Issues" and was quite excited to contribute to, however from reading the comments, you say that this is a project that your working on and implying that these issues aren't actually issues for people to contribute to?!
> 
> Perhaps you should close or delete them all, and not to be rude but I think that you shouldn't of put those tasks as issues in the first place... they aren't really issues instead they are features/parts of the site that you are working on.

@Darsh2987 Yes, I created issues for a project that I'm working on for a programming course because that's literally one the assignment guidelines. The assignment explicitly instructs students to create these issues for the project, which is where the above issue text is coming from. 

Sorry if the existence of these issues confuses you, but I absolutely will not be closing or deleting issues that I've been instructed to create. But thank you anyway for the advice.

**Comment by Godwindaniel10** [comment]
Well, it's great ,of it's an assignment,you don't have to close or delete it. @Darsh2987 was just trying to correct you for future reference. It's cool tho. ☑️
